config/routes.rb
Textpls::Application.routes.draw do
  resources :messages, :only => [:index, :new, :create, :show]

  root to: 'messages#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :to, presence: true
  validates :from, presence: true
  validates :body, presence: true

  before_create :send_sms

  private

  def send_sms
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => 'https://@api.twilio.com/2010-04-01/Accounts/ACfbd6e240902d8750b0d492eb558ecafc/Messages.json',
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :To => to,
                      :From => from,
                      :Body => body }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Your message was sent"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end


  private
    def message_params
      params.require(:message).permit(:to, :from, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Textpls</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <%= link_to "TEXTPLS", root_url, :class => "navbar-text navbar-left" %>
      <%= link_to "New Message", new_message_path, :class => "navbar-text navbar-left" %>
    </div>
  </div>

<div class="container">
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>
</div>


</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<ul>
<% @messages.each do |message| %>
  <li>Message from <%= link_to message.from, message_path(message) %></li>
<% end %>
</ul>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render("layouts/errors", :object => @message) %>

<%= form_for @message do |f| %>
  <div class="form-group">
    <%= f.label :from %></br>
    <%= f.text_field :from %>
  </div>

  <div class="form-group">
    <%= f.label :to %></br>
    <%= f.text_field :to %>
  </div>

  <div class="form-group">
    <%= f.label :body, "Message" %></br>
    <%= f.text_area :body %>
  </div>

  <%= f.submit(:class => "btn btn-primary") %>
<% end %>